### PR TITLE
Update dependencies in Cargo.toml + build instructions

### PR DESCRIPTION
**Pull request by tarcieri**
I was able to build and run the `blink` example on a SAML11 Xplained board with these changes 🎉

ezgif-1-fafa50de908d

(the LED is blinking my attempt at "R-U-S-T" in morse code with some local changes I didn't check in)

Looks like you were able to upstream the `thumbv8m.base-none-eabi` target definition:

https://github.com/rust-lang/rust/pull/55041

I was able to use that via rustup on a recent nightly, so no more need for (patched) xargo.

I went ahead and bumped all of the crates to the latest releases as I wasn't able to get anything to compile without doing so.

### CODE REVIEW

**Comment by tarcieri** [comment]
Also a quick note that I've been doing work on https://github.com/atsamd-rs/atsamd lately (targeting SAMD51) and some of it seems like it might be applicable on these.

I might also be interested in contributing/collaborating on an `embedded-hal` impl for these.

**Comment by evq** [comment]
Awesome, glad to hear it works with nightly and released versions of all the deps!

I have the very early beginnings of a `embedded-hal` implementation crate - just parts of gpio and spi. I used the hal implementation from `atsamd` as a starting point. It's pretty rough - mostly the same code as `atsamd` with bits commented out and a few L11 specific tweaks.

It also has a `rand_core` impl that uses the hardware rng and code to use the rom built-in sha256. 

I'll push it up :)

**Comment by evq** [comment]
@tarcieri Pushed to https://github.com/evq/atsaml11xxx-hal

It's in pretty rough shape - but I upgraded the deps / got the blink example compiling and the host sha256 tests working.

My SAML11 Xplained is being uncooperative so I haven't been able to see if the hal blink is still working.

**Comment by tarcieri** [comment]
@evq nice, thank you!

**Comment by tarcieri** [comment]
@evq since you added `rand_core` support, I'm curious if you have thoughts on this issue: https://github.com/rust-embedded/wg/issues/353

**Pull request merged**
